# Generated by Django 3.1.2 on 2021-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
