# Generated by Django 3.1.2 on 2021-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20210224_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=-1.0),
            preserve_default=False,
        ),
    ]
