# Generated by Django 3.1.2 on 2021-02-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_auto_20210224_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='first_name',
        ),
    ]
