# Generated by Django 3.1.2 on 2021-02-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20210224_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_price',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
