# Generated by Django 3.1.2 on 2021-02-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0008_auto_20210224_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.customer'),
        ),
    ]
