# Generated by Django 3.1.2 on 2021-02-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0010_auto_20210224_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='filter.customer'),
            preserve_default=False,
        ),
    ]
