# Generated by Django 3.1.2 on 2021-02-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0012_auto_20210224_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, related_name='product2', to='filter.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='filter.product'),
        ),
    ]
