# Generated by Django 3.1.2 on 2021-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0013_auto_20210224_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
    ]
