# Generated by Django 3.1.2 on 2021-02-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0015_auto_20210225_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
    ]
