# Generated by Django 3.1.2 on 2021-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0016_remove_order_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='productprice',
            field=models.IntegerField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=20),
        ),
    ]
