# Generated by Django 3.1.2 on 2021-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0020_auto_20210225_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
